# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 51d1c0b0edffc5b9b8ea0d6650dd9ebc970e075a871882dd4c61edec7d9e5faffa39176e32c512841b5fc60f4dc807d9e149d6772774bc34b1f1677624a2ce4b

test:
  secret_key_base: 401dc4b57a44f630d8a5992fc902a25b37a179854655a026cf082d61bc989bb3f391869102226cf64d668309e4550b11fad6074389d7f5ebe3716ee968cf25be

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
